// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma's migration engine (unlike the app's runtime PrismaLibSql
    // adapter in db.js) only ever supports a local `file:` SQLite
    // connection — it cannot reach Turso directly. Migrations are authored
    // here against a local file, then the generated SQL is applied to
    // Turso by hand via `turso db shell` (see README).
    url: "file:./dev.db",
  },
});
